=== CIDARLAB/Parchmint/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "layers": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "name"
                ]
            }
        },
        "connections": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "layer": {
                        "type": "string"
                    },
                    "source": {
                        "type": "object",
                        "properties": {
                            "component": {
                                "type": "string"
                            },
                            "port": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "component",
                            "port"
                        ]
                    },
                    "sinks": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "component": {
                                    "type": "string"
                                },
                                "port": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "component",
                                "port"
                            ]
                        }
                    }
                },
                "required": [
                    "id",
                    "layer",
                    "name",
                    "sinks",
                    "source"
                ]
            }
        },
        "components": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "layers": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "x-span": {
                        "type": "integer"
                    },
                    "y-span": {
                        "type": "integer"
                    },
                    "entity": {
                        "type": "string"
                    },
                    "ports": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "label": {
                                    "type": "string"
                                },
                                "layer": {
                                    "type": "string"
                                },
                                "x": {
                                    "type": "integer"
                                },
                                "y": {
                                    "type": "integer"
                                }
                            },
                            "required": [
                                "label",
                                "layer",
                                "x",
                                "y"
                            ]
                        }
                    }
                },
                "required": [
                    "name",
                    "id",
                    "layers",
                    "x-span",
                    "y-span",
                    "entity",
                    "ports"
                ]
            }
        },
        "features": {
            "definitions": {
                "connection-feature": {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string"
                        },
                        "layer": {
                            "type": "string"
                        },
                        "source": {
                            "type": "object",
                            "properties": {
                                "y": {
                                    "type": "integer"
                                },
                                "x": {
                                    "type": "integer"
                                }
                            },
                            "required": [
                                "x",
                                "y"
                            ]
                        },
                        "sink": {
                            "type": "object",
                            "properties": {
                                "y": {
                                    "type": "integer"
                                },
                                "x": {
                                    "type": "integer"
                                }
                            },
                            "required": [
                                "x",
                                "y"
                            ]
                        },
                        "connection": {
                            "type": "string"
                        },
                        "width": {
                            "type": "integer"
                        },
                        "depth": {
                            "type": "integer"
                        },
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "id",
                        "layer",
                        "name",
                        "type",
                        "source",
                        "sink",
                        "connection"
                    ]
                },
                "component-feature": {
                    "type": "object",
                    "properties": {
                        "layer": {
                            "type": "string"
                        },
                        "x-span": {
                            "type": "integer"
                        },
                        "depth": {
                            "type": "integer"
                        },
                        "location": {
                            "type": "object",
                            "properties": {
                                "y": {
                                    "type": "integer"
                                },
                                "x": {
                                    "type": "integer"
                                }
                            },
                            "required": [
                                "x",
                                "y"
                            ]
                        },
                        "y-span": {
                            "type": "integer"
                        },
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "id",
                        "layer",
                        "name",
                        "depth",
                        "y-span",
                        "location",
                        "x-span"
                    ]
                }
            },
            "type": "array",
            "items": {
                "type": "object",
                "oneOf": [
                    { "$ref": "#/properties/features/definitions/connection-feature" },
                    { "$ref": "#/properties/features/definitions/component-feature" }
                ]
            }
        }
    },
    "required": [
        "name",
        "layers"
    ]
}

=== CIDARLAB/Parchmint/benchmarks/application-converted/planar_synthetic_7.json
{
    "components": [
        {
            "entity": "Input", 
            "id": "83b2ca5e-b86f-4ee4-a23f-2a9c65c615ec", 
            "layers": [
                "af4eba2a-9a9f-4b6b-8113-90b62b62d796"
            ], 
            "name": "Source1", 
            "ports": [
                {
                    "label": "port0", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 10, 
                    "y": 20
                }
            ], 
            "x-span": 20, 
            "y-span": 20
        }, 
        {
            "entity": "Input", 
            "id": "8fd0232f-15e6-4384-9415-c5ccbe2875e3", 
            "layers": [
                "af4eba2a-9a9f-4b6b-8113-90b62b62d796"
            ], 
            "name": "Source2", 
            "ports": [
                {
                    "label": "port0", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 10, 
                    "y": 20
                }
            ], 
            "x-span": 20, 
            "y-span": 20
        }, 
        {
            "entity": "Mixer", 
            "id": "bf4bfe5f-bc69-4132-9597-623f09c61828", 
            "layers": [
                "af4eba2a-9a9f-4b6b-8113-90b62b62d796"
            ], 
            "name": "Mixer1", 
            "ports": [
                {
                    "label": "port0", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 200, 
                    "y": 100
                }, 
                {
                    "label": "port1", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 0, 
                    "y": 100
                }
            ], 
            "x-span": 200, 
            "y-span": 200
        }, 
        {
            "entity": "Mixer", 
            "id": "a5ff8e7a-345d-4810-a9af-b9ecb447b023", 
            "layers": [
                "af4eba2a-9a9f-4b6b-8113-90b62b62d796"
            ], 
            "name": "Mixer2", 
            "ports": [
                {
                    "label": "port0", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 200, 
                    "y": 100
                }, 
                {
                    "label": "port1", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 0, 
                    "y": 100
                }
            ], 
            "x-span": 200, 
            "y-span": 200
        }, 
        {
            "entity": "Mixer", 
            "id": "7f07a019-4cb1-4645-b0af-edb5edef4bd3", 
            "layers": [
                "af4eba2a-9a9f-4b6b-8113-90b62b62d796"
            ], 
            "name": "Mixer3", 
            "ports": [
                {
                    "label": "port0", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 200, 
                    "y": 100
                }, 
                {
                    "label": "port1", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 0, 
                    "y": 100
                }
            ], 
            "x-span": 200, 
            "y-span": 200
        }, 
        {
            "entity": "Mixer", 
            "id": "07963397-1e81-4ebf-a3b9-b2100d916d6f", 
            "layers": [
                "af4eba2a-9a9f-4b6b-8113-90b62b62d796"
            ], 
            "name": "Mixer4", 
            "ports": [
                {
                    "label": "port0", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 200, 
                    "y": 100
                }, 
                {
                    "label": "port1", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 0, 
                    "y": 100
                }
            ], 
            "x-span": 200, 
            "y-span": 200
        }, 
        {
            "entity": "Mixer", 
            "id": "2cf32c4b-5a6b-45b5-a063-8ea93019d549", 
            "layers": [
                "af4eba2a-9a9f-4b6b-8113-90b62b62d796"
            ], 
            "name": "Mixer5", 
            "ports": [
                {
                    "label": "port0", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 200, 
                    "y": 100
                }, 
                {
                    "label": "port1", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 0, 
                    "y": 100
                }
            ], 
            "x-span": 200, 
            "y-span": 200
        }, 
        {
            "entity": "Mixer", 
            "id": "3bffc14f-ef5c-4816-8470-855bc7be2616", 
            "layers": [
                "af4eba2a-9a9f-4b6b-8113-90b62b62d796"
            ], 
            "name": "Mixer6", 
            "ports": [
                {
                    "label": "port0", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 200, 
                    "y": 100
                }, 
                {
                    "label": "port1", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 0, 
                    "y": 100
                }
            ], 
            "x-span": 200, 
            "y-span": 200
        }, 
        {
            "entity": "Mixer", 
            "id": "b9159366-eafb-441e-9110-23c56dc94f6e", 
            "layers": [
                "af4eba2a-9a9f-4b6b-8113-90b62b62d796"
            ], 
            "name": "Mixer7", 
            "ports": [
                {
                    "label": "port0", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 200, 
                    "y": 100
                }, 
                {
                    "label": "port1", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 0, 
                    "y": 100
                }
            ], 
            "x-span": 200, 
            "y-span": 200
        }, 
        {
            "entity": "Mixer", 
            "id": "eb5ee5d4-a123-4175-8e66-0da44a08a385", 
            "layers": [
                "af4eba2a-9a9f-4b6b-8113-90b62b62d796"
            ], 
            "name": "Mixer8", 
            "ports": [
                {
                    "label": "port0", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 200, 
                    "y": 100
                }, 
                {
                    "label": "port1", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 0, 
                    "y": 100
                }
            ], 
            "x-span": 200, 
            "y-span": 200
        }, 
        {
            "entity": "Mixer", 
            "id": "f2696950-0881-4417-bf3b-0c84f3596a8a", 
            "layers": [
                "af4eba2a-9a9f-4b6b-8113-90b62b62d796"
            ], 
            "name": "Mixer9", 
            "ports": [
                {
                    "label": "port0", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 200, 
                    "y": 100
                }, 
                {
                    "label": "port1", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 0, 
                    "y": 100
                }
            ], 
            "x-span": 200, 
            "y-span": 200
        }, 
        {
            "entity": "Mixer", 
            "id": "8fb8babf-19f0-4442-87c8-a3291dda6f3b", 
            "layers": [
                "af4eba2a-9a9f-4b6b-8113-90b62b62d796"
            ], 
            "name": "Mixer10", 
            "ports": [
                {
                    "label": "port0", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 200, 
                    "y": 100
                }, 
                {
                    "label": "port1", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 0, 
                    "y": 100
                }
            ], 
            "x-span": 200, 
            "y-span": 200
        }, 
        {
            "entity": "Mixer", 
            "id": "a9698f8b-f5ac-45c7-a1b6-1d14c84446de", 
            "layers": [
                "af4eba2a-9a9f-4b6b-8113-90b62b62d796"
            ], 
            "name": "Mixer11", 
            "ports": [
                {
                    "label": "port0", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 200, 
                    "y": 100
                }, 
                {
                    "label": "port1", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 0, 
                    "y": 100
                }
            ], 
            "x-span": 200, 
            "y-span": 200
        }, 
        {
            "entity": "Mixer", 
            "id": "1781503b-a6ec-4274-b164-080a33c88761", 
            "layers": [
                "af4eba2a-9a9f-4b6b-8113-90b62b62d796"
            ], 
            "name": "Mixer12", 
            "ports": [
                {
                    "label": "port0", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 200, 
                    "y": 100
                }, 
                {
                    "label": "port1", 
                    "layer": "af4eba2a-9a9f-4b6b-8113-90b62b62d796", 
                    "x": 0, 
                    "y": 100
                }
            ], 
            "x-span": 200, 
            "y-span": 200
        },
